### ISSUE TITLE
support latest Intercom API

### ISSUE THREAD

**Issue by spang** [jkeyes/python-intercom#47] opened 2015-01-28 21:31 UTC
Hi there,

This doesn't seem to support the latest Intercom API, and instead uses the v1 API. Are there any plans to support the latest API?

http://doc.intercom.io/api/#intercom-api

Some documentation links from the old API docs do not work anymore, and new features are only available with the new API.

Thanks for writing these Python bindings!

**Comment by flc** [comment] 2015-02-18 17:13
There is an apiv2 branch, might worth a try. Works for me so far but I only tried basic stuff, like managing users.
@jkeyes how stable would you consider the code in the apiv2 branch?

**Comment by nerdburn** [comment] 2015-03-02 00:32
Ping! Very interested in this as well.

**Comment by Madd** [comment] 2015-03-09 11:06
How is the development going for v2?

**Comment by jkeyes** [comment] 2015-03-09 12:41
The truth of the matter is that I've had no time to dedicate to this for a while now. I'm not sure what state the v2 API is in. FWIR it was supporting the majority of the features from the v1 API. I don't know how stable it is as I haven't compared to the latest API docs. Sorry I can't be clearer about this.

**Comment by greenafrican** [comment] 2015-03-16 21:07
Chatted to Intercom today and they don't have any plans to release a Python client anytime soon so will be great to bring this fantastic project inline with the v2 API. Thanks for the work to date.

**Comment by flc** [comment] 2015-03-16 22:24
I got the same response from them about a month ago: "... we've no immediate plans to add more client libraries at the minute ...". I'm using the apiv2 branch of my fork in production. No problem with it so far, but I'm only using a few endpoints: users, events, conversations/messages.

**Comment by jkeyes** [comment] 2015-03-16 23:22
I'm reviewing the branch now. My gut tells me it's in pretty good shape. I just need to verify that. I'm currently comparing features against the official Ruby library.

**Comment by jkeyes** [comment] 2015-03-17 00:24
BTW folks, any help is welcome.

**Comment by jkeyes** [comment] 2015-03-18 09:24
I compared the tests from intercom-ruby with python-intercom and I think there is only one big difference between the two and that's error handling support. I'll start work on this next and then review the open issues.

**Comment by flc** [comment] 2015-03-18 16:02
I needed to make some changes/fixes in my fork, you can take a look at them and decide whether you want to apply them. Because of your recent changes there are some merge conflicts now: https://github.com/jkeyes/python-intercom/compare/apiv2...flc:apiv2

**Comment by flc** [comment] 2015-03-18 16:08
Also, how can I run the tests? It would probably worth a mention in the readme or somewhere. Thanks

**Comment by flc** [comment] 2015-03-18 16:19
ah, ok, sorry, it's here: http://python-intercom.readthedocs.org/en/latest/development.html#running-the-tests. I was misled a bit by this: https://github.com/jkeyes/python-intercom/blob/apiv2/dev-requirements.txt

I get a lot of 
```
from intercom import HttpError
ImportError: cannot import name HttpError
```

**Comment by jkeyes** [comment] 2015-03-18 16:42
apiv2 is using describe for running the unit tests. I'll add it to the README. The docs are out of date as they are for v1 of the API.

**Comment by greenafrican** [comment] 2015-03-19 08:12
Yeah, even simple things like 
```
from intercom import User
ImportError: cannot import name User
```
Which is now lowercase:
```
from intercom import user
```

And the `.all()` method is now uppercase `.All()`. 

@jkeyes - I can to help update the apiv2 docs as I go through everything - assuming the new standards are correct?

**Comment by jkeyes** [comment] 2015-03-19 10:26
@greenafrican (I got your comment via email but no sign in the Github UI) I'm hoping to fix the structure so you can do ```from intercom import User``` style imports. I don't think you should do any documentation updates until I've confirmed that, as it might just be a waste of your time.

There is no change to ```all```, for example: https://github.com/jkeyes/python-intercom/blob/apiv2/tests/unit/collection_proxy_spec.py#L29

**Comment by jkeyes** [comment] 2015-03-19 10:27
@flc I've applied some of your changes to the apiv2 branch. Thanks.

**Comment by flc** [comment] 2015-03-19 10:29
@jkeyes cool, thanks for your efforts!

**Comment by greenafrican** [comment] 2015-03-19 10:31
@jkeyes yeah sorry for that I deleted the comment as I figured out i was being stupid. The change is
`from intercom.user import User` and then `User.all()`. When I had the original error I was tab searching on the object and found `user.All()`. Yeah I think it best for you to decide on standards etc and then I can help with docs if you like. Also just chatted to Intercom again and they sounded vaguely keen to get behind you and this project, but I don't know how that will ultimately translate.

**Comment by jkeyes** [comment] 2015-03-19 10:34
@flc I'll get to the custom attributes one too. I just want to look at the ruby lib to see what they do.

**Comment by jkeyes** [comment] 2015-03-19 10:34
@greenafrican Ah-ha! I didn't even consider any code-completion tools when writing it. My process is to follow the ruby lib as much as possible so it'll be easy to keep up with any changes they make. What IDE are you using?

**Comment by jkeyes** [comment] 2015-03-19 10:35
@greenafrican No comment is stupid BTW. I'll set up a new site blamethedocs.org :wink:

**Comment by greenafrican** [comment] 2015-03-19 10:35
@jkeyes using PyCharm and iPython Notebooks

**Comment by grantmcconnaughey** [comment] 2015-03-24 20:22
What work is left to be done before API v2 can be merged and deployed to PyPI? I'd like to help out if I can.

**Comment by jkeyes** [comment] 2015-03-24 21:17
@grantmcconnaughey Code wise it's just about ready for release. If you want you could start reviewing the current docs. I'd be interested in hearing everyone's thoughts about the docs actually.

My approach for them was to copy the structure of the Intercom docs for the Ruby library. I was going to run with the same format for v2. What do you think?

**Comment by grantmcconnaughey** [comment] 2015-03-24 21:27
I like the idea of mimicking the Ruby library. I think that will help the odds of this package being picked up by Intercom as the official Python Intercom library (assuming you are cool with that).

**Comment by jkeyes** [comment] 2015-03-24 21:28
If they want it, they can have it. I know a few of the folks working in there, we've a good relationship.

**Comment by grantmcconnaughey** [comment] 2015-03-24 21:42
I do like the big README.rst documentation. Are you wanting that to be the sole documentation for the Python API? And does python-intercom actually have all the functionality that is displayed in the README, or is that what the goal is?

**Comment by jkeyes** [comment] 2015-03-24 21:47
They do the README too (that's where I grabbed it from). They also have full API docs here: http://docs.intercom.io/api I *think* python-intercom supports all of the cases in the README. If you look in the tests/integration directory you'll find code for each of the entries in the README. I'm trying to improve those tests right now, and I'm working through some issues I've found with Intercom. 

The v1 docs for python-intercom are here: http://python-intercom.readthedocs.org/en/latest/

**Comment by jkeyes** [comment] 2015-03-26 12:15
The integrations tests (which were written to mirror the README) are validated to be working. I'll review the intercom-ruby README next and see if all of the cases are covered.

**Comment by grantmcconnaughey** [comment] 2015-03-26 16:12
@jkeyes I compared the two READMEs and found only a few differences:

* `MultipleMatchingUsersError` is in the intercom-ruby but not intercom-python
* `HttpError` is in intercom-ruby but not intercom-python
* intercom-python is missing the final section on Rate Limiting (calling `Intercom.rate_limit_details`)

**Comment by jkeyes** [comment] 2015-03-26 16:29
Thanks @grantmcconnaughey. I definitely have the tests for the first two in place.  Just wrapping up Python 3 support then I'll get back to this.

**Comment by jkeyes** [comment] 2015-03-27 11:42
Python 3 support now in `apiv2`.

**Comment by jkeyes** [comment] 2015-03-27 18:16
Count support now in `apiv2` e.g. Count.user_counts_for_each_tag.

**Comment by grantmcconnaughey** [comment] 2015-03-27 18:20
You're good people, @jkeyes. My company is integrating Intercom in our application starting next week. We'd be happy to beta test python-intercom.

**Comment by jkeyes** [comment] 2015-03-27 18:25
@grantmcconnaughey Do please, and file all the bug reports :wink:

**Comment by grantmcconnaughey** [comment] 2015-03-27 19:11
Are you planning on putting 2.0 beta up on PyPI? Or do we need to add the github repo to our requirements.txt file?

**Comment by jkeyes** [comment] 2015-03-27 19:58
Yeah I think it's in a state that can go on PyPI soon. Might get that done tomorrow.

**Comment by jkeyes** [comment] 2015-03-28 14:10
Ready to go code wise in `apiv2`. Documentation work next.

**Comment by jkeyes** [comment] 2015-03-29 00:35
I've updated the documentation, and merged apiv2 (including dodgy merge commit – doh!) to master.

**Closed by jkeyes** 2015-03-29 00:35 UTC
