### ISSUE TITLE
NoneType returned on user email change

### ISSUE THREAD

**Issue by greenafrican** [jkeyes/python-intercom#87] opened 2015-04-10 09:31 UTC
Hi @jkeyes thanks for the beta release!

Interesting edge-case but if I do this
`user = User.create(email="bob@example.com", user_id=1)
print type(user)`

I get `<class 'intercom.user.User'>` as expected.

However, if my user decides to ever change their email address for their account:
`user = User.create(email="not_bob@example.com", user_id=1)
print type(user)`

I get a `<type 'NoneType'>` response and can't continue to add custom_attributes etc or `.save` etc. On Intercom, i see that `bob@example.com` either no longer exists and/or is overwritten as expected with not_bob@example.com which is correct (all activity still remains so I am guessing the user object hasn't been changed).

**Comment by jkeyes** [comment] 2015-04-10 09:46
@greenafrican I just tried the following:

    user = User.create(email="bob@example.com", user_id=1002)
    print user, type(user), user.email
    user = User.create(email="not_bob@example.com", user_id=1002)
    print user, type(user), user.email

and saw this output:

    <intercom.user.User object at 0x1040b6cd0> <class 'intercom.user.User'> bob@example.com
    <intercom.user.User object at 0x103f5d0d0> <class 'intercom.user.User'> not_bob@example.com

We need to try to narrow this down.

**Comment by greenafrican** [comment] 2015-04-10 10:33
Ok, working through it. Seems to only sometimes happen. Trying to find the exact replicable scenario.

**Comment by jkeyes** [comment] 2015-04-10 10:54
My guess (and it's exactly that) is that an empty response is coming back from Intercom.

**Comment by greenafrican** [comment] 2015-04-10 10:57
It may be a corrupted record on Intercom's side as it is only happening with 1 user. The user definitely exists (https://cloudup.com/cb28msIbp0y) but when I do
```
user = User.find(user_id=440)
print user, type(user), user.email
...
HttpError: Http Error - No response entity returned
```

and 

```
user = User.create(email="bob@example.com", user_id=440)
print user, type(user), user.email
...
AttributeError: 'NoneType' object has no attribute 'email'
```

Will follow up with Intercom and come back to you.

**Comment by jkeyes** [comment] 2015-04-10 11:01
I've seen similar before, when I was trying to increment a session count. It worked without problem in all cases I tried except one. The following day that one worked too. I raised this with Intercom at the time.

**Comment by greenafrican** [comment] 2015-04-10 11:06
Yeah, looks like even Intercom battling to wrangle this record - https://cloudup.com/cs4mZ1WSgGA

Returns 0 results. Let's see what they say.

**Comment by greenafrican** [comment] 2015-04-10 12:00
This may be worth checking out:
```
user = User.create(email="bob@example.com", user_id=440)
print user, type(user), user.email
 None <type 'NoneType'>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-59-c482b8a96c92> in <module>()
      1 user = User.create(email="bob@example.com", user_id=440)
----> 2 print user, type(user), user.email

AttributeError: 'NoneType' object has no attribute 'email'
```

BUT, this works:
```
$ curl https://api.intercom.io/users \
> -X POST \
> -u xxx:xxx \
> -H 'Accept: application/json' \
> -H 'Content-Type: application/json' -d '
> {
>   "user_id": 440,
>   "email": "bob@example.com"
>  }
> '
{
    "type": "user",
    "id": "xxx",
    "user_id": "440",
    "anonymous": false,
    "email": "bob@example.com",
    "name": null,
    "pseudonym": null,
    "avatar": {
        "type": "avatar",
        "image_url": "xxx"
    },
    "app_id": "xxx",
    "companies": {
        "type": "company.list",
        "companies": [
            {
                "type": "company",
                "company_id": "437",
                "id": "xxx",
                "name": "Example"
            }
        ]
    },
    "location_data": {
       etc..
    },
    "last_request_at": 1428588906,
    "last_seen_ip": "xxx",
    "created_at": 1426851786,
    "remote_created_at": 1421413873,
    "signed_up_at": 1421413873,
    "updated_at": 1428666696,
    "session_count": 1,
    "social_profiles": {
        "type": "social_profile.list",
        "social_profiles": []
    },
    "unsubscribed_from_emails": false,
    "user_agent_data": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36",
    "tags": {
        "type": "tag.list",
        "tags": []
    },
    "segments": {
        "type": "segment.list",
        "segments": [
            {
                "type": "segment",
                "id": "xxx"
            },
            {
                "type": "segment",
                "id": "xxx"
            },
            {
                "type": "segment",
                "id": "xxx"
            }
        ]
    },
    "custom_attributes": {
        "Active": true,
        "Email Activated": true,
        "Staff": false
    }
}
```

And then... of course:
```
$ curl \
> -s https://api.intercom.io/users/440 \
> -u xxx:xxx \
> -H 'Accept:application/json'
{"type":"error.list","request_id":"xxx","errors":[{"code":"not_found","message":"User Not Found"}]}
```
and
```
user = User.find(user_id=440)
print user, type(user), user.email, user.companies
...
HttpError: Http Error - No response entity returned
```

Which are at least consistent.

**Comment by greenafrican** [comment] 2015-04-10 15:40
Expecting some feedback from Intercom in this thread.

**Comment by erskingardner** [comment] 2015-04-10 16:18
Hey guys, 

Jeff, from Intercom, here. 

First off. `https://api.intercom.io/users/{user_id}` isn't valid, you can only pass the Intercom ID of the user in that way and get a valid user back. To get a user back using the user_id you'll need to make a request to `https://api.intercom.io/users?user_id={user_id}`. So it makes sense that you'd be getting a 404 for that request. 

@greenafrican I'll follow up with you in Intercom but I'm not seeing anything odd in the logs for your app and this user.

**Comment by jkeyes** [comment] 2015-04-10 19:16
Hey Jeff. To be clear python-intercom doesn't send requests to `https://api.intercom.io/users/{user_id}` it follows the same pattern as intercom-ruby. See [find.py](https://github.com/jkeyes/python-intercom/blob/master/intercom/api_operations/find.py#L13) for details.

I haven't been able to reproduce the problem yet.

**Comment by greenafrican** [comment] 2015-04-11 14:27
Thanks @erskingardner for clarifying. I was just testing. I can confirm that `curl` returns the correct user Intercom object for the id.

```
$ curl \
> -s https://api.intercom.io/users/xxxxxxx \
> -u xxx:xxx \
> -H 'Accept:application/json'
```

```
{
    "type": "user",
    "id": "xxx",
    "user_id": "440",
    "anonymous": false,
    "email": "bob@example.com",
    "name": null,
    "pseudonym": null,
    "avatar": {
        "type": "avatar",
        "image_url": "xxx"
    },
    "app_id": "xxx",
    "companies": {
        "type": "company.list",
        "companies": [
            {
                "type": "company",
                "company_id": "437",
                "id": "xxx",
                "name": "Example"
            }
        ]
    },
    "location_data": {
       etc..
    },
    "last_request_at": 1428588906,
    "last_seen_ip": "xxx",
    "created_at": 1426851786,
    "remote_created_at": 1421413873,
    "signed_up_at": 1421413873,
    "updated_at": 1428666696,
    "session_count": 1,
    "social_profiles": {
        "type": "social_profile.list",
        "social_profiles": []
    },
    "unsubscribed_from_emails": false,
    "user_agent_data": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36",
    "tags": {
        "type": "tag.list",
        "tags": []
    },
    "segments": {
        "type": "segment.list",
        "segments": [
            {
                "type": "segment",
                "id": "xxx"
            },
            {
                "type": "segment",
                "id": "xxx"
            },
            {
                "type": "segment",
                "id": "xxx"
            }
        ]
    },
    "custom_attributes": {
        "Active": true,
        "Email Activated": true,
        "Staff": false
    }
}
```

**Comment by erskingardner** [comment] 2015-04-13 12:38
Thanks for clarifying guys, @jkeyes I really don't think that this is an issue on the library so feel free to close this and I'll continue following up with @greenafrican in Intercom.

**Comment by jkeyes** [comment] 2015-04-16 09:18
@erskingardner Cool. Let me know if there's anything that needs to be supported on this end.

**Comment by erskingardner** [comment] 2015-04-17 10:58
Hey @jkeyes, circling back here. The 2.0.beta library does appear to be the source of this odd one. The response hasn't changed on our end and as @greenafrican said, the curl response comes back immediately with the right type and data.

**Comment by greenafrican** [comment] 2015-04-17 11:21
Two responses from:
```
 curl -s https://api.intercom.io/users/xxx \
> -u xxx:xxx \
> -H 'Accept:application/json'
```
May help to look at 1 that works and another that fails. Eyeballing it, maybe `Fürth` in the city name causing the issue?


Here is an example of a user object response that works:
```
{
    "type": "user",
    "id": "xxx",
    "user_id": "10",
    "anonymous": false,
    "email": "another@example.com",
    "name": null,
    "pseudonym": null,
    "avatar": {
        "type": "avatar",
        "image_url": "xxx"
    },
    "app_id": "xxx",
    "companies": {
        "type": "company.list",
        "companies": [
            {
                "type": "company",
                "company_id": "7",
                "id": "xxx",
                "name": "example"
            }
        ]
    },
    "location_data": {
        "type": "location_data",
        "city_name": "Polokwane",
        "continent_code": "AF",
        "country_name": "South Africa",
        "latitude": xxx,
        "longitude": xxx,
        "postal_code": "xxx",
        "region_name": "Limpopo",
        "timezone": "Africa/Johannesburg",
        "country_code": "ZAF"
    },
    "last_request_at": 1428599261,
    "last_seen_ip": "xxx",
    "created_at": 1426769458,
    "remote_created_at": 1407336095,
    "signed_up_at": 1407336095,
    "updated_at": 1429248896,
    "session_count": 3,
    "social_profiles": {
        "type": "social_profile.list",
        "social_profiles": []
    },
    "unsubscribed_from_emails": false,
    "user_agent_data": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36",
    "tags": {
        "type": "tag.list",
        "tags": []
    },
    "segments": {
        "type": "segment.list",
        "segments": [
            {
                "type": "segment",
                "id": "xxx"
            },
            {
                "type": "segment",
                "id": "xxx"
            },
            {
                "type": "segment",
                "id": "xxx"
            }
        ]
    },
    "custom_attributes": {
        "is_active": true,
        "email_activated": true,
        "is_staff": false,
        "Email Activated": true,
        "Active": true,
        "Staff": false
    }
}
```


Here is an example of a user object response that fails:
```
{
    "type": "user",
    "id": "xxx",
    "user_id": "602",
    "anonymous": false,
    "email": "bob@example.com",
    "name": null,
    "pseudonym": null,
    "avatar": {
        "type": "avatar",
        "image_url": null
    },
    "app_id": "xxx",
    "companies": {
        "type": "company.list",
        "companies": [
            {
                "type": "company",
                "company_id": "599",
                "id": "xxx",
                "name": "example"
            }
        ]
    },
    "location_data": {
        "type": "location_data",
        "city_name": "Fürth",
        "continent_code": "EU",
        "country_name": "Germany",
        "latitude": xx,
        "longitude": xx,
        "postal_code": "xx",
        "region_name": "Bayern",
        "timezone": "Europe/Berlin",
        "country_code": "DEU"
    },
    "last_request_at": 1428333010,
    "last_seen_ip": "xxx",
    "created_at": 1428006179,
    "remote_created_at": 1428009744,
    "signed_up_at": 1428009744,
    "updated_at": 1429249406,
    "session_count": 21,
    "social_profiles": {
        "type": "social_profile.list",
        "social_profiles": []
    },
    "unsubscribed_from_emails": false,
    "user_agent_data": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:37.0) Gecko/20100101 Firefox/37.0",
    "tags": {
        "type": "tag.list",
        "tags": []
    },
    "segments": {
        "type": "segment.list",
        "segments": [
            {
                "type": "segment",
                "id": "xxx"
            },
            {
                "type": "segment",
                "id": "xxx"
            },
            {
                "type": "segment",
                "id": "xxx"
            }
        ]
    },
    "custom_attributes": {
        "Active": true,
        "Email Activated": true,
        "Staff": false
    }
}
```

**Comment by jkeyes** [comment] 2015-04-17 22:03
@erskingardner @greenafrican Rightio.

**Comment by jkeyes** [comment] 2015-04-17 22:21
I've tested by mocking a response as follows:

        response = Mock()
        response.content = API_RESPONSE
        response.encoding = 'utf-8'
        response.status_code = 200

where `API_RESPONSE` is the JSON (both users) shown above. This is working as expected. I'm going to add some logging support which may help us locate the problem.

**Comment by jkeyes** [comment] 2015-04-17 23:02
@greenafrican I've added some request logging (https://github.com/jkeyes/python-intercom/tree/request-logging). Please run your test with logging turned on and share the output with me.

Here's a super simple config to get logging to `stderr`:

    import logging
    logger = logging.getLogger('intercom')
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    logger.addHandler(ch)

Thanks.

**Comment by greenafrican** [comment] 2015-04-20 07:18
@jkeyes Ok, i've tried with logging and all records that previously didn't work are now working?! So I guess something somewhere changed.

```
from intercom import User

user = User.find(email='bob@example.com')
print user, type(user)
```

```
Sending GET request to: https://api.intercom.io/users
DEBUG:intercom.request:Sending GET request to: https://api.intercom.io/users
  headers: {'Accept': 'application/json', 'User-Agent': 'python-intercom/2.0.beta'}
DEBUG:intercom.request:  headers: {'Accept': 'application/json', 'User-Agent': 'python-intercom/2.0.beta'}
  params: {'email': 'bob@example.com'}
DEBUG:intercom.request:  params: {'email': 'bob@example.com'}
Response received from https://api.intercom.io/users
DEBUG:intercom.request:Response received from https://api.intercom.io/users
  encoding=utf-8 status:200
DEBUG:intercom.request:  encoding=utf-8 status:200
```

```
<intercom.user.User object at 0x103ccbf50> <class 'intercom.user.User'>
```

If I uninstall `request-logging` and re-install `2.0.beta` I get the errors again:
https://cloudup.com/cHOARvA1VpW

**Comment by jkeyes** [comment] 2015-04-20 11:13
Thanks for the update @greenafrican. It's a strange one. As you can see from [the diff](https://github.com/jkeyes/python-intercom/compare/request-logging) the only changes were to add some logging code.

**Comment by greenafrican** [comment] 2015-04-20 11:22
Yeah I looked at that. Very odd. Is the latest `master` branch = `2.0.beta` tag? What is the latest PyPi package? I currently install with:
```
pip install python-intercom==2.0.beta
```

and for the request-logging used:
```
pip install git+https://github.com/jkeyes/python-intercom.git@request-logging
```

but just `pip install python-intercom` looks like version 0.2.13.

**Comment by jkeyes** [comment] 2015-04-25 12:42
@greenafrican Yeah the default on PyPi is still 0.2.13. I don't think there's a way to change that. I'd like to get this issue resolved before publishing 2.0 officially.

**Comment by greenafrican** [comment] 2015-05-31 20:29
Hi @jkeyes just some feedback on this again. I'm pretty sure it has to do with encoding somewhere. Here are a few customers that cause this issue - https://cloudup.com/cSWHr5-cRCy

Still running 2.0.beta

**Comment by jkeyes** [comment] 2016-03-21 21:31
@greenafrican I'm wondering if you've tried this with the `version-3` branch yet. I haven't done anything specifically to address this issue, just wondering. Thanks.

**Comment by jkeyes** [comment] 2017-02-15 01:51
@greenafrican It's been a long time since I've updated this issue. I just ran a test on version 3.1.0 by creating a user  (`client.users.create`) and associating them with a company named `Fürth`. I then changed the email and saved the update to Intercom (`client.users.save`).

I'm going to close the issue, but if you're still having this issue let me know and we'll try to get to the bottom of it.

**Closed by jkeyes** 2017-02-15 01:51 UTC
